### ISSUE TITLE
Add HTTPS Git urls for bruw git open command

### ISSUE THREAD

**Issue by MoretS** [Quentinchampenois/bruw#8]
Hi @Quentinchampenois!

It seems that this is not possible to use `bruw git open` command with HTTPS remote links.
Here is a sample with a HTTPS link ⬇️ 

```bash
git remote -v | grep origin | cut -d' ' -f1 | head -n1   

# output
origin  https://github.com/MoretS/bruw.git 
```
```ruby
path = "origin  https://github.com/MoretS/bruw.git".split
path[1].split(":")[1].split(".")[0]
=> "//github" 
```

<img width="1791" alt="Capture d’écran 2021-10-16 à 00 56 12" src="https://user-images.githubusercontent.com/51788811/137562611-6b9c39c7-a55e-44a4-b487-71c41e4cd1cc.png">

Do you consider it's ok to implement HTTPS links compatibilty?

If yes, got a PR for you : https://github.com/Quentinchampenois/bruw/pull/7
Thanks!

**Comment by Quentinchampenois** [comment]
Thanks for your issue and pull Request, I merged your work. I now close this issue since it is fixed.
